unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256colorwRGB"

set -g prefix C-Space

set -g mouse on

# sane copy pasting 
set-option -g set-clipboard on
set-window-option -g mode-keys vi

bind -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard -i"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -selection clipboard -i"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# create new session
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind w new-window -c "#{pane_current_path}"
bind v split-window -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

# Bind <prefix> + x to switch to the 'kill-mode' table for the next keypress
bind x switch-client -T kill-mode
bind -T kill-mode p kill-pane
bind -T kill-mode w kill-window

set-option -g status-position top

# set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g status-left ""
set -g status-right "#{Ew@catppuccin_status_application} #{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
